/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webgl2frame_free: (a: number, b: number) => void;
export const webgl2frame_new: (a: any) => [number, number, number];
export const webgl2frame_set_projection: (a: number) => void;
export const webgl2frame_update_scene: (a: number, b: any) => [number, number];
export const rust_error: (a: number, b: number) => void;
export const rust_info: (a: number, b: number) => void;
export const rust_super_super_verbose: (a: number, b: number) => void;
export const rust_super_verbose: (a: number, b: number) => void;
export const rust_verbose: (a: number, b: number) => void;
export const rust_warn: (a: number, b: number) => void;
export const set_fps: (a: number) => void;
export const __wbg_enginewebgl2_free: (a: number, b: number) => void;
export const enginewebgl2_new: (a: any) => [number, number, number];
export const enginewebgl2_update_scene: (a: number, b: any) => [number, number];
export const initialize_web_gl: (a: any) => [number, number, number];
export const update_scene: (a: number, b: any) => [number, number, number];
export const disable_rotate_x: () => void;
export const disable_rotate_y: () => void;
export const disable_rotate_z: () => void;
export const enable_rotate_x: () => void;
export const enable_rotate_y: () => void;
export const enable_rotate_z: () => void;
export const wasm_bindgen__closure__destroy__h21ad5149ab061324: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hfd7dd9b55ab67e19: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h34e51b1b792f4171: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
